# Generated by Django 5.0.3 on 2024-04-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.FileField(blank=True, upload_to='profiles'),
        ),
    ]
