# Generated by Django 5.0.3 on 2024-04-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='products')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
